### ISSUE TITLE
Rotation 

### ISSUE THREAD

**Issue by emilewakim96** [RcuDev/SimpleMediaPlayer#4]
Thank you for your app code.
However, Device rotation while player is running is not handled

**Comment by RcuDev** [comment]
I @emilewakim96. Thanks for the feedback. I go to review the issue now.

**Comment by pattersonjack** [comment]
@RcuDev Thanks for this excellent resource!

Removing the `stopService` call in the activity's `onDestroy` method appears to work well, although this means we need to stop the service someplace else. Adding `stopWithTask="true"` to the manifest or overriding `onTaskRemoved` in the service are two possibilities that come to mind. However, I'd like to hear if you have any other ideas for cleanly stopping the service.

**Comment by maxrave-dev** [comment]
> Thank you for your app code. However, Device rotation while player is running is not handled

Add this to your 'activity' tag in AndroidManifest

`android:configChanges="keyboardHidden|orientation|screenSize"`

**Comment by RcuDev** [comment]
Thank you all for the feedback. I haven't had much time to update and review it. I try to do it during these days :).

**Comment by RcuDev** [comment]
Thanks a lot @maxrave-dev , this fix de rotation issue :). 

I go to close this issue.
